### PR TITLE
Use Shared props/targets

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp.Drawing/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

- Updates the solution to use the shared props/targets
- Cleans up all warnings in the solution.
- Adds Mac OSX CI workflow plus additional enhancements from ImageSharp.

### CODE REVIEW

**Review by antonfirsov — CHANGES_REQUESTED** [review]
Didn't get to drawing yet, but I see 999 build warnings in main lib's ImageSharp.Test project per build target. We should fix that before propagating the rules further.

Most of them are "this should not follow that" and underscore rules we do not wan to apply in test code.

**Comment by JimBobSquarePants** [comment]
>Didn't get to drawing yet, but I see 999 build warnings in main lib's ImageSharp.Test project per build target. We should fix that before propagating the changes further.

I don't think your submodule is loaded properly or something. I brought it down to zero from over 1200 warnings.

**Comment by antonfirsov** [comment]
@JimBobSquarePants ah sorry you may be right will doublecheck tomorrow!

**Review by antonfirsov — APPROVED** [review]
@JimBobSquarePants this ImageSharp.Drawing PR is fine, but still I get those warnings with the main library's test project even on a fresh clone on master. (After standard `git submodule update --init --recursive`).

Nice job cleaning up the Drawing project, and the overall effort across the SixLabors infra. No idea why is it OK here and not OK there.

**Comment by antonfirsov** [comment]
Opened SixLabors/ImageSharp#1460 to properly track the problem.

**Pull request merged**
