### PR TITLE
Update shared infrastructure

### PR DESCRIPTION
**Pull request by brianpopow**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp.Drawing/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Update shared infrastructure for the ImageSharp.Drawing project.

### CODE REVIEW

**Comment by brianpopow** [comment]
@JimBobSquarePants there are still some errors left in the test project like:

`##[error]Processing/FakeImageOperationsProvider.cs(12,50): error CS0281: Friend access was granted by 'SixLabors.ImageSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13', but the public key of the output assembly ('') does not match that specified by the InternalsVisibleTo attribute in the granting assembly. `

from a quick google search, it seems related to strong naming ImageSharp. Unfortunately i have no experience with that. If you know more about that please let me know.

**Comment by brianpopow** [comment]
Ok no more build errors, i have signed ImageSharp.Drawing.Tests.csproj with key from shared-infrastructure, see: 080acf2b0f4db675f0aa58e18dfacb5dddcdefa4. Still some failing tests. I will try to figure out whats wrong here.

**Comment by JimBobSquarePants** [comment]
@brianpopow There's nothing in your changes that would cause differences. Could you post an example of two differing images?

@antonfirsov I'm a little concerned that https://github.com/SixLabors/ImageSharp/pull/1143 may have  caused more issues here.

**Comment by brianpopow** [comment]
> @brianpopow There's nothing in your changes that would cause differences. Could you post an example of two differing images?

@JimBobSquarePants 
The failing test is in SolidFillBlendedShapesTests: `_1DarkBlueRect_2BlendHotPinkRect_3BlendTransparentEllipse`

This is the actual image output: 
actual

This is the expected one:
expected

They look the same but they are not, the square in the middle is different. Where the actual output has Rgba32(0, 0, 0, 0), the expected has Rgba32(255, 255, 255, 0).

Here is an image where the difference pixels are marked red:
output

**Comment by JimBobSquarePants** [comment]
> Rgba32(0, 0, 0, 0), the expected has Rgba32(255, 255, 255, 0)

@brianpopow That makes me think that the expected result is actually incorrect. I wonder, do we premultiply in the pipeline anywhere?

**Comment by brianpopow** [comment]
> > Rgba32(0, 0, 0, 0), the expected has Rgba32(255, 255, 255, 0)
> 
> @brianpopow That makes me think that the expected result is actually incorrect. I wonder, do we premultiply in the pipeline anywhere?

Premultiply is not used here. I dont think my changes have introduced this, so im keen in changing the reference images. @JimBobSquarePants should i do that?

**Comment by JimBobSquarePants** [comment]
@brianpopow I figured it out! 

The tests use `Color.Transparent` which used to be `255,255,255,0` but is now `0,0,0,0`. 

Update the references :+1:

**Comment by brianpopow** [comment]
> The tests use `Color.Transparent` which used to be `255,255,255,0` but is now `0,0,0,0`.

great, that explains its. 
Reference images are changed now.

**Comment by JimBobSquarePants** [comment]
@brianpopow I fixed the build/signing issues for you also. Thanks for doing this, I'll merge it now.

**Comment by brianpopow** [comment]
> @brianpopow I fixed the build/signing issues for you also. Thanks for doing this, I'll merge it now.

thanks, i could not figure out the problem

**Pull request merged**
