### PR TITLE
Fix compatibility with .NET 5 SDK InternalsVisibleTo

### PR DESCRIPTION
**Pull request by antonfirsov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp.Drawing/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
Same thing as SixLabors/ImageSharp#1337. My Rider is configured with .NET 5 SDK so I need this now.

### CODE REVIEW

**Comment by antonfirsov** [comment]
No idea why does this fail for 2.1 😞

**Comment by JimBobSquarePants** [comment]
@antonfirsov The issue is unrelated. GitHub have changed the images.
https://github.com/SixLabors/ImageSharp/commit/398e3a7d143040bedf65a4d213960becddfcff0f#diff-c2079db070ee682627c591c8361a58c2

We also need to update CodeCov
https://github.com/SixLabors/ImageSharp/commit/f0ed1b766bdbfef6fe6fd019529fa5f718882255#diff-c2079db070ee682627c591c8361a58c2

**Review by tocsoft — APPROVED** [review]

**Comment by antonfirsov** [comment]
@JimBobSquarePants thanks!

**Comment by JimBobSquarePants** [comment]
No worries. I should fix Fonts also, will do it this weekend.

**Pull request merged**
